import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

export const metadata: Metadata = {
  title: "CodexMattrix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="mt-13  lg:mt-10 xl:mt-15 2xl:mt-15">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
